-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS proy_concesionaria.carro
(
    numero_chasis integer,
    id_marca proy_concesionaria.d_id,
    modelo character varying,
    color_p character varying,
    anio integer,
    tipo_caja character,
    precio money,
    id_carro proy_concesionaria.d_id,
    id_proveedor proy_concesionaria.d_id,
    id_categoria proy_concesionaria.d_id,
    PRIMARY KEY (id_carro)
);

CREATE TABLE IF NOT EXISTS proy_concesionaria.cliente
(
    id_cliente proy_concesionaria.d_id,
    nombres proy_concesionaria.d_nomb_ape,
    apellidos proy_concesionaria.d_nomb_ape,
    telefono proy_concesionaria.d_telefono,
    cedula proy_concesionaria.d_cedula,
    direccion proy_concesionaria.d_direccion,
    PRIMARY KEY (id_cliente)
);

CREATE TABLE IF NOT EXISTS proy_concesionaria.empleado
(
    id_empleado proy_concesionaria.d_id,
    nombres proy_concesionaria.d_nomb_ape,
    apellidos proy_concesionaria.d_nomb_ape,
    telefono proy_concesionaria.d_telefono,
    cedula proy_concesionaria.d_cedula,
    PRIMARY KEY (id_empleado)
);

CREATE TABLE IF NOT EXISTS proy_concesionaria.factura
(
    id_factura proy_concesionaria.d_id,
    id_cliente proy_concesionaria.d_id,
    id_concesionario proy_concesionaria.d_id,
    fecha_factura proy_concesionaria.d_fecha,
    id_empleado proy_concesionaria.d_id,
    id_tipo_pago proy_concesionaria.d_id,
    PRIMARY KEY (id_factura)
);

CREATE TABLE IF NOT EXISTS proy_concesionaria.concesionaria
(
    id_concesionario proy_concesionaria.d_id,
    nombre_concesionario proy_concesionaria.d_nomb_ape,
    direccion_concesionario character varying,
    PRIMARY KEY (id_concesionario)
);

CREATE TABLE IF NOT EXISTS proy_concesionaria.detalle_factura
(
    id_carro proy_concesionaria.d_id,
    id_factura proy_concesionaria.d_id,
    cantidad integer,
    precio money,
    PRIMARY KEY (id_factura, id_carro)
);

CREATE TABLE IF NOT EXISTS proy_concesionaria.proveedor
(
    id_proveedor proy_concesionaria.d_id,
    nombre proy_concesionaria.d_nomb_ape,
    PRIMARY KEY (id_proveedor)
);

CREATE TABLE IF NOT EXISTS proy_concesionaria.marcas
(
    id_marca proy_concesionaria.d_id,
    nombre_marca proy_concesionaria.d_nomb_ape,
    PRIMARY KEY (id_marca)
);

CREATE TABLE IF NOT EXISTS proy_concesionaria.categorias
(
    id_categoria proy_concesionaria.d_id,
    nombre proy_concesionaria.d_nomb_ape,
    PRIMARY KEY (id_categoria)
);

CREATE TABLE IF NOT EXISTS proy_concesionaria.tipo_pago
(
    id_tipo_pago proy_concesionaria.d_id,
    tipo_pago proy_concesionaria.d_nomb_ape,
    PRIMARY KEY (id_tipo_pago)
);

ALTER TABLE IF EXISTS proy_concesionaria.carro
    ADD FOREIGN KEY (id_proveedor)
    REFERENCES proy_concesionaria.proveedor (id_proveedor) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS proy_concesionaria.carro
    ADD FOREIGN KEY (id_marca)
    REFERENCES proy_concesionaria.marcas (id_marca) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS proy_concesionaria.carro
    ADD FOREIGN KEY (id_categoria)
    REFERENCES proy_concesionaria.categorias (id_categoria) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS proy_concesionaria.factura
    ADD FOREIGN KEY (id_cliente)
    REFERENCES proy_concesionaria.cliente (id_cliente) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS proy_concesionaria.factura
    ADD FOREIGN KEY (id_concesionario)
    REFERENCES proy_concesionaria.concesionaria (id_concesionario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS proy_concesionaria.factura
    ADD FOREIGN KEY (id_empleado)
    REFERENCES proy_concesionaria.empleado (id_empleado) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS proy_concesionaria.factura
    ADD FOREIGN KEY (id_tipo_pago)
    REFERENCES proy_concesionaria.tipo_pago (id_tipo_pago) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS proy_concesionaria.detalle_factura
    ADD FOREIGN KEY (id_factura)
    REFERENCES proy_concesionaria.factura (id_factura) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS proy_concesionaria.detalle_factura
    ADD FOREIGN KEY (id_carro)
    REFERENCES proy_concesionaria.carro (id_carro) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;